blender_path: "C:\\Program Files\\Blender Foundation\\Blender 5.1\\blender.exe"

scene: "data/references/cubes.blend"

engine: "CYCLES"

cycles_settings:
  device: "CUDA"
  samples: 4

reference: "data/references/ref/cubes_Cycles_CUDA_ref.png"

repeat: 1

wait: 10
