blender_path: "/home/oliwialinux/Documents/blender-5.1.2-linux-x64/blender"

scene: "data/references/bakery.blend"

engine: "CYCLES"

cycles_settings:
  device: "GPU"
  samples: 512

reference: "data/references/ref/bakery_Cycles_GPU_ref.png"

repeat: 10

wait: 600
