blender_path: "/home/oliwialinux/Documents/blender-5.1.2-linux-x64/blender"

scene: "data/references/cubes.blend"

engine: "CYCLES"

cycles_settings:
  device: "CUDA"
  samples: 128

reference: "data/references/ref/cubes_Cycles_GPU_ref.png"

repeat: 10

wait: 600
