blender_path: "C:\\Program Files\\Blender Foundation\\Blender 5.1\\blender.exe"

scene: "data/references/cubes.blend"

engine: "BLENDER_EEVEE"

eevee_settings:
  profile: "LOW"
  samples: 4

reference: "data/references/ref/cubes_Eevee_ref.png"

repeat: 2

wait: 5
