blender_path: "/home/oliwialinux/Documents/blender-5.1.2-linux-x64/blender"

scene: "data/references/cubes.blend"

engine: "BLENDER_EEVEE"

eevee_settings:
  profile: "MEDIUM"
  samples: 8

reference: "data/references/ref/cubes_Eevee_8.png"

repeat: 10

wait: 600
