blender_path: "/home/oliwialinux/Documents/blender-5.1.2-linux-x64/blender"

scene: "data/references/bakery.blend"

engine: "BLENDER_EEVEE"

eevee_settings:
  profile: "HIGH"
  samples: 16

reference: "data/references/ref/bakery_Eevee_ref.png"

repeat: 10

wait: 300
